name: 📄 Deploy GitHub Pages

on:
  workflow_run:
    workflows: ["🧪 Playwright Tests"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: 📥 Download Playwright Report
      uses: actions/download-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
    
    - name: 🚀 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        destination_dir: .
